# Generated by Django 4.1.5 on 2023-01-18 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WordList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Word List name"),
                ),
                (
                    "name_ru",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=256,
                        null=True,
                        verbose_name="Russian Word List name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Word List description",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Adding date and time"
                    ),
                ),
                (
                    "access",
                    models.BooleanField(
                        choices=[(False, "Private"), (True, "Public")],
                        default=True,
                        verbose_name="Public access",
                    ),
                ),
                (
                    "native",
                    models.BooleanField(
                        default=False, verbose_name="Native community word list"
                    ),
                ),
                (
                    "parse",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="For a quick addition, add one word per line in English.",
                        null=True,
                        verbose_name="Add many words.",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_lists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Word List author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Words list",
                "verbose_name_plural": "Words lists",
                "ordering": ["-native", "author", "name"],
            },
        ),
        migrations.CreateModel(
            name="WordListSubscriplion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Subscriplion date and time"
                    ),
                ),
                (
                    "rate",
                    models.PositiveIntegerField(
                        default=None, null=True, verbose_name="Daily rate"
                    ),
                ),
                (
                    "list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_list_subscriplion",
                        to="words.wordlist",
                        verbose_name="Word list",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_list_subscriplion",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Follower",
                    ),
                ),
            ],
            options={
                "verbose_name": "Word-list subscriplion",
                "verbose_name_plural": "Word-list subscriplions",
                "ordering": ["user", "-created"],
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "en",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="English word"
                    ),
                ),
                (
                    "ru",
                    models.CharField(
                        max_length=128, verbose_name="Russian translation"
                    ),
                ),
                (
                    "example",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Example of usage",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Adding date and time"
                    ),
                ),
                (
                    "list",
                    models.ManyToManyField(
                        related_name="words",
                        to="words.wordlist",
                        verbose_name="Words list",
                    ),
                ),
            ],
            options={
                "verbose_name": "Word",
                "verbose_name_plural": "Words",
                "ordering": ["en"],
            },
        ),
        migrations.AddConstraint(
            model_name="wordlistsubscriplion",
            constraint=models.UniqueConstraint(
                fields=("user", "list"), name="unique_subscriplion"
            ),
        ),
        migrations.AddConstraint(
            model_name="wordlist",
            constraint=models.UniqueConstraint(
                fields=("name", "author"), name="unique_name_by_author"
            ),
        ),
    ]
