# Generated by Django 4.1.5 on 2023-01-21 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("words", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tranclation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="date of creation",
                    ),
                ),
                ("tr", models.CharField(max_length=128, verbose_name="Translation")),
                ("native", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="word",
            name="native",
        ),
        migrations.AlterField(
            model_name="word",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="date of creation"
            ),
        ),
        migrations.AlterField(
            model_name="wordlist",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="date of creation"
            ),
        ),
        migrations.AlterField(
            model_name="wordlistsubscriplion",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="date of creation"
            ),
        ),
        migrations.CreateModel(
            name="WordTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="date of creation",
                    ),
                ),
                (
                    "cost",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordering value"
                    ),
                ),
                (
                    "native",
                    models.BooleanField(
                        default=True, verbose_name="Native translation"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author of translation",
                    ),
                ),
                (
                    "translation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word",
                        to="words.tranclation",
                        verbose_name="Translation",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation",
                        to="words.word",
                        verbose_name="Word",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
