# Generated by Django 4.1.5 on 2023-01-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="audio_uk",
            field=models.BinaryField(null=True, verbose_name="GB pronunciation"),
        ),
        migrations.AddField(
            model_name="word",
            name="audio_us",
            field=models.BinaryField(null=True, verbose_name="USA pronunciation"),
        ),
    ]
