# Generated by Django 4.1.5 on 2023-01-21 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0002_tranclation_remove_word_native_alter_word_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tranclation",
            options={
                "ordering": ["tr"],
                "verbose_name": "Translation",
                "verbose_name_plural": "Translations",
            },
        ),
        migrations.AlterModelOptions(
            name="wordtranslation",
            options={
                "ordering": ["native", "word"],
                "verbose_name": "Word Translation",
                "verbose_name_plural": "Word Translations",
            },
        ),
        migrations.RemoveField(
            model_name="tranclation",
            name="native",
        ),
    ]
