# Generated by Django 4.1.5 on 2023-01-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0002_word_audio_uk_word_audio_us"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="audio_uk",
            field=models.BinaryField(
                default=None, null=True, verbose_name="GB pronunciation"
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="audio_us",
            field=models.BinaryField(
                default=None, null=True, verbose_name="USA pronunciation"
            ),
        ),
    ]
