# Generated by Django 4.1.5 on 2023-01-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0003_alter_tranclation_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tranclation",
            new_name="Translation",
        ),
    ]
