# Generated by Django 4.1.5 on 2023-01-29 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("words", "0003_alter_word_audio_uk_alter_word_audio_us"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordLearn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="date of creation",
                    ),
                ),
                (
                    "step",
                    models.IntegerField(
                        choices=[
                            (0, "Skip"),
                            (1, "Read"),
                            (2, "Option"),
                            (3, "Write"),
                            (4, "Pass"),
                        ],
                        verbose_name="Step",
                    ),
                ),
                ("result", models.BooleanField(verbose_name="Result")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words_learn",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Learner",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words_learn",
                        to="words.word",
                        verbose_name="Learned word",
                    ),
                ),
            ],
            options={
                "verbose_name": "Word learning log",
                "verbose_name_plural": "Words learning log",
                "ordering": ["created"],
            },
        ),
    ]
