# Generated by Django 4.1.5 on 2023-02-02 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("words", "0004_wordlearn"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordListSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="date of creation",
                    ),
                ),
                (
                    "rate",
                    models.PositiveIntegerField(
                        default=None, null=True, verbose_name="Daily rate"
                    ),
                ),
                (
                    "list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_list_subscription",
                        to="words.wordlist",
                        verbose_name="Word list",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_list_subscriplion",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Follower",
                    ),
                ),
            ],
            options={
                "verbose_name": "Word-list subscriplion",
                "verbose_name_plural": "Word-list subscriplions",
                "ordering": ["user", "-created"],
            },
        ),
        migrations.DeleteModel(
            name="WordListSubscriplion",
        ),
        migrations.AddConstraint(
            model_name="wordlistsubscription",
            constraint=models.UniqueConstraint(
                fields=("user", "list"), name="unique_subscriplion"
            ),
        ),
    ]
