# Generated by Django 4.1.5 on 2023-01-17 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Registration date and time",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="language_code",
            field=models.CharField(
                default=None,
                max_length=4,
                null=True,
                verbose_name="Language code",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tg_id",
            field=models.BigIntegerField(
                unique=True, verbose_name="Telegram id"
            ),
            preserve_default=False,
        ),
    ]
