# Generated by Django 4.1.5 on 2023-01-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Adding date and time"
            ),
        ),
    ]
