# Generated by Django 4.1.5 on 2023-01-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="tg_page",
            new_name="TgPage",
        ),
    ]
