# Generated by Django 4.1.5 on 2023-01-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_rename_tg_page_tgpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tgpage",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="date of creation"
            ),
        ),
    ]
