# Generated by Django 4.1.5 on 2023-02-05 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="date of creation",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Collection name"),
                ),
                (
                    "name_translated",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=256,
                        null=True,
                        verbose_name="Translated Collection name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Collection description",
                    ),
                ),
                (
                    "access",
                    models.BooleanField(
                        choices=[(False, "Private"), (True, "Public")],
                        default=True,
                        verbose_name="Public access enabled",
                    ),
                ),
                (
                    "native",
                    models.BooleanField(
                        default=False, verbose_name="Native community word list"
                    ),
                ),
                (
                    "parse",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="For a quick addition, add one word per line in English.",
                        null=True,
                        verbose_name="Add many words.",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Collection author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
                "ordering": ["-native", "author", "name"],
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="date of creation",
                    ),
                ),
                ("tr", models.CharField(max_length=128, verbose_name="Translation")),
            ],
            options={
                "verbose_name": "Translation",
                "verbose_name_plural": "Translations",
                "ordering": ["tr"],
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="date of creation",
                    ),
                ),
                (
                    "en",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="English word"
                    ),
                ),
                (
                    "audio_us",
                    models.BinaryField(
                        default=None, null=True, verbose_name="USA pronunciation"
                    ),
                ),
                (
                    "audio_uk",
                    models.BinaryField(
                        default=None, null=True, verbose_name="GB pronunciation"
                    ),
                ),
                (
                    "example",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Example of usage",
                    ),
                ),
                (
                    "collection",
                    models.ManyToManyField(
                        related_name="words",
                        to="words.collection",
                        verbose_name="collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Word",
                "verbose_name_plural": "Words",
                "ordering": ["en"],
            },
        ),
        migrations.CreateModel(
            name="WordTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="date of creation",
                    ),
                ),
                (
                    "cost",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordering value"
                    ),
                ),
                (
                    "native",
                    models.BooleanField(
                        default=True, verbose_name="Native translation"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author of translation",
                    ),
                ),
                (
                    "translation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word",
                        to="words.translation",
                        verbose_name="Translation",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation",
                        to="words.word",
                        verbose_name="Word",
                    ),
                ),
            ],
            options={
                "verbose_name": "Word Translation",
                "verbose_name_plural": "Word Translations",
                "ordering": ["native", "word"],
            },
        ),
        migrations.CreateModel(
            name="WordLearn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="date of creation",
                    ),
                ),
                (
                    "step",
                    models.IntegerField(
                        choices=[
                            (0, "Skip"),
                            (1, "Read"),
                            (2, "Option"),
                            (3, "Write"),
                            (4, "Pass"),
                        ],
                        verbose_name="Step",
                    ),
                ),
                ("result", models.BooleanField(verbose_name="Result")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words_learn",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Learner",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words_learn",
                        to="words.word",
                        verbose_name="Learned word",
                    ),
                ),
            ],
            options={
                "verbose_name": "Word learning log",
                "verbose_name_plural": "Words learning log",
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="CollectionSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="date of creation",
                    ),
                ),
                (
                    "rate",
                    models.PositiveIntegerField(
                        default=None, null=True, verbose_name="Daily rate"
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_subscription",
                        to="words.collection",
                        verbose_name="Collection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_list_subscriplion",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Follower",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection subscriplion",
                "verbose_name_plural": "Collection subscriplions",
                "ordering": ["user", "-created"],
            },
        ),
        migrations.AddConstraint(
            model_name="collectionsubscription",
            constraint=models.UniqueConstraint(
                fields=("user", "collection"), name="unique_subscriplion"
            ),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                fields=("name", "author"), name="unique_name_by_author"
            ),
        ),
    ]
